routes:
  /:
    get:
      sequential: true
      responses:
        - code: 200
          data: |
            {
              "some": "data",
              "to": "return"
            }
        - code: 500
          data: "{\"error\": \"something went wrong\"}"
  /animals:
    post:
      responses:
        - code: 204
          data: ""
    get:
      responses:
        - code: 200
          data: |
            [
              {
                "animal": "dog",
                "name": "spot"
              }
            ]
  /animals/:name/details:
    get:
      responses:
        - code: 200
          data: |
            {
              "animal": "bear",
              "name": "{{ index .Vars "name" }}"
            }
  /animals/:name/food:
    get:
      responses:
        - code: 200
          data: |
            {
              "animal": "bear",
              "food": ["salmon", "berries"]
            }
default:
  responses:
    - code: 200
      data: |
        {"default": true}
